Repository umass-lrc/database, pull requests merged in 2022-07, with the labels that each got.

#24 Add course adding and editing features
  lrc_database/main/forms.py
  lrc_database/main/templates/courses/add_course.html
  lrc_database/main/templates/courses/edit_course.html
  lrc_database/main/templates/courses/view_course.html
  lrc_database/main/templates/includes/navbar.html
  lrc_database/main/urls.py
  lrc_database/main/views.py
Labels: Feature

#26 Move to pyproject.toml-based configuration, update makefile, add caching to GitHub actions
  .github/workflows/automated_checks.yml
  Makefile
  lrc_database/main/admin.py
  lrc_database/main/forms.py
  lrc_database/main/management/commands/bootstrapdatabase.py
  lrc_database/main/models.py
  pyproject.toml
  setup.cfg
Labels: DevOps

#25 User creation
  .gitignore
  lrc_database/main/forms.py
  lrc_database/main/models.py
  lrc_database/main/templates/includes/navbar.html
  lrc_database/main/templates/users/create_user.html
  lrc_database/main/templates/users/create_users_in_bulk.html
  lrc_database/main/templates/users/user_profile.html
  lrc_database/main/urls.py
  lrc_database/main/views.py
Labels: User management, Feature

#23 Hardware loans
  lrc_database/main/forms.py
  lrc_database/main/models.py
  lrc_database/main/templates/hardware/add_hardware.html
  lrc_database/main/templates/hardware/edit_hardware.html
  lrc_database/main/templates/hardware/hardware_table.html
  lrc_database/main/templates/loans/add_loans.html
  lrc_database/main/templates/loans/edit_loans.html
  lrc_database/main/templates/loans/show_loans.html
  lrc_database/main/urls.py
  lrc_database/main/views.py
  lrc_database/manage.py
  setup.cfg
Labels: Hardware loans, Feature

#29 Add page for dropping shifts on a day, Docker changes, many smaller things
  .github/workflows/build_docker_images.yml
  .gitignore
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  lrc_database/lrc_database/settings.py
  lrc_database/main/static/css/main.css
  lrc_database/main/templates/base.html
  lrc_database/main/templates/includes/navbar.html
  lrc_database/main/templates/shifts/drop_shifts_on_date.html
  lrc_database/main/templates/shifts/drop_shifts_on_date_confirmation.html
  lrc_database/main/urls.py
  lrc_database/main/views/__init__.py
  lrc_database/main/views/bulk_shift_editing_views.py
  nginx/nginx.conf
  production.yml
  pyproject.toml
Labels: Shift scheduling, Feature, DevOps

#30 Update nginx Dockerfile to track mainline instead of 1.21
  nginx/Dockerfile
Labels: DevOps

#38 Create Dependabot configuration
  .github/dependabot.yml
Labels: DevOps

#37 Remove setup.cfg, since we use pyproject.toml now
  setup.cfg
Labels: DevOps
